export const LEAVE_REQUEST_CREATE_REQUEST = 'LEAVE_REQUEST_CREATE_REQUEST';
export const LEAVE_REQUEST_CREATE_SUCCESS = 'LEAVE_REQUEST_CREATE_SUCCESS';
export const LEAVE_REQUEST_CREATE_FAIL = 'LEAVE_REQUEST_CREATE_FAIL';


// Leave request action types
export const LEAVE_REQUEST_LIST_REQUEST = 'LEAVE_REQUEST_LIST_REQUEST';
export const LEAVE_REQUEST_LIST_SUCCESS = 'LEAVE_REQUEST_LIST_SUCCESS';
export const LEAVE_REQUEST_LIST_FAIL = 'LEAVE_REQUEST_LIST_FAIL';


export const LEAVE_REQUEST_LIST_REQUEST_ADMIN = 'LEAVE_REQUEST_LIST_REQUEST_ADMIN';
export const LEAVE_REQUEST_LIST_SUCCESS_ADMIN = 'LEAVE_REQUEST_LIST_SUCCESS_ADMIN';
export const LEAVE_REQUEST_LIST_FAIL_ADMIN = 'LEAVE_REQUEST_LIST_FAIL_ADMIN';

export const LEAVE_REQUEST_UPDATE_REQUEST = 'LEAVE_REQUEST_UPDATE_REQUEST';
export const LEAVE_REQUEST_UPDATE_SUCCESS = 'LEAVE_REQUEST_UPDATE_SUCCESS';
export const LEAVE_REQUEST_UPDATE_FAIL = 'LEAVE_REQUEST_UPDATE_FAIL';

export const LEAVE_REQUEST_UPDATE_RESET='LEAVE_REQUEST_UPDATE_RESET'

