export const USER_CHECK_IN_REQUEST = "USER_CHECK_IN_REQUEST";
export const USER_CHECK_IN_SUCCESS = "USER_CHECK_IN_SUCCESS";
export const USER_CHECK_IN_FAIL = "USER_CHECK_IN_FAIL";
export const USER_CHECK_IN_RESET = "USER_CHECK_IN_RESET";

export const USER_CHECK_OUT_REQUEST = "USER_CHECK_OUT_REQUEST";
export const USER_CHECK_OUT_SUCCESS = "USER_CHECK_OUT_SUCCESS";
export const USER_CHECK_OUT_FAIL = "USER_CHECK_OUT_FAIL";
export const USER_CHECK_OUT_RESET = "USER_CHECK_OUT_RESET";

export const GET_TODAYS_ATTENDANCE_REQUEST = "GET_TODAYS_ATTENDANCE_REQUEST";
export const GET_TODAYS_ATTENDANCE_SUCCESS = "GET_TODAYS_ATTENDANCE_SUCCESS";
export const GET_TODAYS_ATTENDANCE_FAIL = "GET_TODAYS_ATTENDANCE_FAIL";

export const GET_ALL_ATTENDANCE_REQUEST = "GET_ALL_ATTENDANCE_REQUEST";
export const GET_ALL_ATTENDANCE_SUCCESS = "GET_ALL_ATTENDANCE_SUCCESS";
export const GET_ALL_ATTENDANCE_FAIL = "GET_ALL_ATTENDANCE_FAIL";
export const GET_ALL_ATTENDANCE_RESET="GET_ALL_ATTENDANCE_RESET"

export const GET_ALL_USERS_ATTENDANCE_REQUEST = "GET_ALL_USERS_ATTENDANCE_REQUEST";
export const GET_ALL_USERS_ATTENDANCE_SUCCESS = "GET_ALL_USERS_ATTENDANCE_SUCCESS";
export const GET_ALL_USERS_ATTENDANCE_FAIL = "GET_ALL_USERS_ATTENDANCE_FAIL";
export const GET_ALL_USERS_ATTENDANCE_RESET="GET_ALL_USERS_ATTENDANCE_RESET"


